FROM tomcat:9.0
COPY target/event-app.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 6060
CMD ["catalina.sh","run"]

docker build -t newimage .
docker run --name image -d newimage 
docker tag newimage username/pushimage